PS2/next/android/urls.py
from django.urls import path, include
from rest_framework import routers
from django.conf.urls.static import static
from django.conf import settings

from .views import add_app, Home_view, MyApp_View, complete_task,Task_View, add_new, Delete,AppViewSet,points

router = routers.SimpleRouter()
router.register(r'apps', AppViewSet)

app_name = 'android'
urlpatterns = [
    path('api/', include(router.urls)),
    path('add-app/<int:pk>', add_app, name='add_app'),
    path('complete/<int:pk>',complete_task, name = 'complete'),
    path('task',Task_View.as_view(),name = 'task'),
    path('',Home_view,name = 'home'),
    path('myapps/',MyApp_View.as_view(),name = 'my_app'),
    path('add_new',add_new, name = 'add_new'),
    path('delete/<int:pk>',Delete, name = 'delete'),
    path('points',points,name = 'points'),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PS2/next/next/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls' )),

    path('',include('android.urls', namespace = 'android')),

]

PS2/next/android/models.py
from django.db import models
from django.conf import settings
from .category import Choice


class App(models.Model):
    name = models.CharField(max_length = 100)
    applink = models.CharField(max_length = 200)
    app_category = models.CharField(max_length = 50, choices = Choice)
    sub_category = models.CharField(max_length = 50,choices = Choice)
    points = models.IntegerField(default = 0)
    img = models.FileField(upload_to = 'media')

    def __str__(self):
        return self.name



class Task(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    apps = models.ForeignKey(App, on_delete = models.CASCADE, related_name='related_items')
    points = models.IntegerField(default = 0)
    screenshot = models.FileField(upload_to = 'media', null = True)
    task_completed = models.BooleanField(default = False)

    def __str__(self):
        return self.user.username

class UserDownloads(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete =models.CASCADE)
    apps = models.ForeignKey(App,on_delete = models.CASCADE)
    visited = models.BooleanField(default = False)

    def __str__(self):
        return self.user.username

PS2/next/android/forms.py
from django import forms
from .models import Task, App
from .category import Choice

#Form for verifying the app downlaod
class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('screenshot',)

#Form for adding the new app by the admin
class AppForm(forms.ModelForm):

    # app_category = forms.ChoiceField(choices = Choice,  widget=forms.Select(),required = True)
    # sub_category = forms.ChoiceField(choices = Choice, widget=forms.Select(), required = True)
    
    class Meta:
        model = App
        fields = ('name', 'applink','points','img','app_category','sub_category',)
        widgets = {
            'app_category' : forms.Select(choices = Choice),
            'sub_category' : forms.Select(choices = Choice),
        }

PS2/next/android/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView
from django.http import HttpResponseRedirect, HttpResponse
from .forms import TaskForm, AppForm
from rest_framework import permissions
from django.contrib import messages
from .models import Task, App, UserDownloads
from rest_framework import viewsets
from .serializers import AppSerializer

class AppViewSet(viewsets.ModelViewSet):
    queryset = App.objects.all()
    serializer_class = AppSerializer
    permission_classes = [permissions.IsAuthenticated]

    
def Home_view(request):
    context = {}
    context['items'] = App.objects.all()
    if request.user.is_superuser:
        return render(request,'admin_home.html', context)
    if request.user.is_authenticated:
        return render(request, 'home.html', context)
    return HttpResponse('<h2><a href="accounts/login">LOGIN REQUIRED</a></h2>')
    
def Delete(request, pk, template_name='delete.html'):
    book = get_object_or_404(App, pk=pk)    
    if request.method=='POST':
        book.delete()
        return HttpResponseRedirect('/')
    return render(request, template_name, {})


def add_new(request):
    if request.method == 'POST':
        form = AppForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit = False)
            form.save()
            return HttpResponseRedirect('/')

    else:
        form = AppForm()
    return render(request, 'add_app.html', {
        'form': form
    })

def add_app(request, pk):
    item = get_object_or_404(App, pk = pk)
    query_set = UserDownloads.objects.filter(user = request.user, visited = True)
    if query_set.exists(): 
        cn = 0
        for i in range(0,len(query_set)):
            # print(pk)
            # print(query_set[i].apps.pk, 'pkss')
            if(pk == query_set[i].apps.pk):
                messages.success(request, 'App already added')
                cn = 1
                break
        if cn == 0:
            UserDownloads.objects.create(user = request.user, apps = item, visited = True)
    
    else:
        UserDownloads.objects.create(user = request.user, apps = item, visited = True)
    return HttpResponseRedirect('/')

def complete_task(request, pk):
    item = get_object_or_404(UserDownloads, pk = pk)
    query_set = Task.objects.filter(user = request.user, task_completed = True)
    key = item.apps.pk
    if query_set.exists():
        cn = 0
        for i in range(len(query_set)):
            if key == query_set[i].apps.pk:
                messages.success(request, 'Task Already Completed')
                cn = 1
                break
            else:
                continue
        if cn == 0:
            if request.method == 'POST':
                print('s')
                form = TaskForm(request.POST, request.FILES)
                if form.is_valid():
                    obj = form.save(commit = False)
                    obj.user = request.user
                    obj.apps = item.apps
                    obj.points =  item.apps.points
                    obj.task_completed = True
                    form.save()
                    return HttpResponseRedirect('/')
            else:
                form = TaskForm()
            return render(request, 'file.html',{'form' : form})
        # else:
        #     HttpResponseRedirect('/')

    else:
        # Task.objects.create(user = request.user, apps = item.apps, points = item.apps.points, task_completed = True)
        if request.method == 'POST':
            form = TaskForm(request.POST, request.FILES)
            if form.is_valid():
                obj = form.save(commit = False)
                obj.user = request.user
                obj.apps = item.apps
                obj.points =  item.apps.points
                obj.task_completed = True
                form.save()
                return HttpResponseRedirect('/')
            # Task.objects.create(user = request.user, apps = item.apps, points = item.apps.points, task_completed = True)
        else:
            form = TaskForm()
        return render(request, 'file.html',{'form' : form})
    
    return HttpResponseRedirect('/myapps')




class MyApp_View(ListView):
    model = UserDownloads
    template_name = 'my_apps.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = UserDownloads.objects.filter(user = self.request.user)

        return context

class Task_View(TemplateView):
    model = Task
    template_name = 'task.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = Task.objects.filter(user = self.request.user)
        total = 0
        for i in context['items']:
            total = total + i.points
        context['total'] = total
 
        return context

def points(request):
    total = 0
    for i in Task.objects.filter(user = request.user):
        total+=i.points
    context = {}
    context['t'] = total
    return render(request, 'po.html', context)

PS2/next/android/templates/add_app.html
<form action="#" method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{form.as_p}}
    <button type = "submit">Upload</button>
</form>

{% if messages %}
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
{% endif %}

 

PS2/next/android/templates/admin_home.html
{% extends 'b.html' %}


{% block content %}
<div>
    {% if user.is_superuser %}
    {% for item in items %}
        <h2>{{item.name}} {{item.points}}</h2>
        <img src="{{item.img.url}}" alt="NO">
        <h3><a href="{% url 'android:delete' item.id %}">Delete</a> </h3>
    {% endfor %}
{% endif %}

</div>
{% endblock %}

PS2/next/android/templates/b.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

PS2/next/android/templates/delete.html
<h1>File Delete</h1>
<form method="post">{% csrf_token %}
    Delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

PS2/next/android/templates/file.html
<form action="#" method = "POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.media }}
  {{form.as_p}}
  <button type = "submit">Upload</button>
</form>

PS2/next/android/templates/home.html
{% extends 'b.html' %}


{% block content %}

<div>
    {% if user.is_authenticated %}
    {% for item in items %}
        <h2>{{item.name}}</h2>
        <img src="{{item.img.url}}" alt="NO">
        <h3><a href="{% url 'android:add_app' item.id %}">ADD</a> </h3>
    {% endfor %}
{% endif %}

</div>
{% if messages %}
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
{% endif %}
{% endblock %}

PS2/next/android/templates/my_apps.html
{% extends 'b.html' %}

{% block content %}
{% for item in items %}
    <h2>{{item.apps}}</h2>
    <img src="{{item.apps.img.url}}" alt="NO">
    <a href="{% url 'android:complete' item.id %}">Complete Task</a>

{% endfor %}
{% if messages %}
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
{% endif %}
{% endblock %}

PS2/next/android/templates/navbar.html
<h1>Hello {{user}}</h1>

<style>
    ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
}

li {
  float: left;
}

li a {
  font-size: large;
  display: block;
  padding: 8px;
  text-decoration: underline;
  color: black;

}
</style>

{% if user.is_superuser %}
<nav>
    <ul>
        <li>
            <a href="{% url 'android:add_new' %}">Add Apps</a>
        </li>
        <li>
            <a href="{% url 'android:home' %}">Home</a>
        </li>
        <li>
            <a href="{% url 'account_logout' %}">Logout</a>
        </li>
    </ul>
</nav>
{% else %}
    <nav>
        <ul>
            <li>
                <a href="/">Home</a>
            </li>
            <li>
                <a href="{% url 'android:my_app' %}">Profile</a>
            </li>
            <li>
                <a href="{% url 'android:task' %}">Task</a>
            </li>
            <li>
                <a href="{% url 'android:points' %}">Points</a>
            </li>
            <li>
                <a href="{% url 'account_logout' %}">Logout</a>
            </li>

        </ul>

    
    </nav>
    
{% endif %}

PS2/next/android/templates/po.html
{% extends 'b.html' %}

{% block content %}
<h2>{{t}}</h2>

{% endblock %} 

PS2/next/android/templates/points.html
{% extends 'b.html' %}
{% block content %}
<h1>You Have {{total}} </h1> 
{% endblock content %}

PS2/next/android/templates/task.html
{% extends 'b.html' %}
{% block content %}

{% for item in items %}
    <h2>{{item.apps}} {{item.points}} </h2>
    <img src="{{item.apps.img.url}}" alt="NO">
{% endfor %}


{% endblock content %}